DROP DATABASE APPTRY;

CREATE DATABASE APPTRY;
USE APPTRY;

CREATE TABLE T_Server (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	ipAddress VARCHAR(50) NOT NULL,
	port INTEGER NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE T_Application (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	md5 VARCHAR(128),
	name VARCHAR(50),
	aliasName VARCHAR(50),
	size BIGINT UNSIGNED,
	packageName VARCHAR(100),
	version VARCHAR(20),
	os VARCHAR(20),
	startActivity VARCHAR(200),
	icon BLOB,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE T_Emulator (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	server_id INTEGER UNSIGNED NOT NULL,
	serialNumber VARCHAR(50) NOT NULL,
	manufacturer VARCHAR(20),
	model VARCHAR(20),
	os VARCHAR(20),
	width INTEGER UNSIGNED NOT NULL,
	height INTEGER UNSIGNED NOT NULL,
	dpi VARCHAR(20),
	state TINYINT UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE T_Deployment (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
	application_id INTEGER UNSIGNED NOT NULL,
	emulator_id INTEGER UNSIGNED NOT NULL,
	PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;